### PR TITLE
add os matrix to github workflow

### PR DESCRIPTION
**Pull request by fractalcactus**

### CODE REVIEW

**Comment by fractalcactus** [comment]
the os `macos-latest` is failing because:
"Note: If your workflows use Docker container actions or service containers, then you must use a Linux runner"
https://docs.github.com/en/actions/configuring-and-managing-workflows/about-service-containers

**Comment by fractalcactus** [comment]
currently not possible

**Comment by eoinkelly** [comment]
Thanks for chasing this down all the same!

**Comment by joshmcarthur** [comment]
Also noting that build minutes are consumed 10x faster for Mac OS and 2x for Windows

https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Pull request closed without merging**
