### PR TITLE
feat: setup testing library for typescript too

### PR DESCRIPTION
**Pull request by G-Rath**
In future I'd like to have some more components and tests to serve as examples of some of the common cases we know people will come across with both React and TypeScript, but for now this'll do.

### CODE REVIEW

**Comment by G-Rath** [comment]
Whoops I spaced and forgot we've already got some different components in the TypeScript variant.

**Comment by G-Rath** [comment]
I've gone with just removing extra components because it was hard coming up with meaningful tests for them so now I've just converted the react variant to TypeScript.

In future I would really like to have some more default content as there's a couple of stuff I think is worth showcasing (like how to type react components), but it's better to have this variant working now than try and wait for me to get some spare time.

**Comment by G-Rath** [comment]
I've also renamed the test config to `react-typescript` and enabled the React variant since right now that is really what our `typescript` variant is.

Now that it looks like we've both warmed up to TypeScript a bit & are moving towards using Stimulus before React I'm going to try and create an independent TypeScript variant.

**Comment by eoinkelly** [comment]
Code looks fine to me. I think the decision to make TS the default for all our future React work is significant enough to warrant sign-off from multiple devs. In particular, @joshmcarthur and @mischa-s who I know have been working in it a lot recently.

**Comment by eoinkelly** [comment]
Also this PR should update the README to explain that our React variant requires TS

**Comment by G-Rath** [comment]
> to explain that our React variant requires TS

I think there's some confusion: this doesn't make TypeScript required for our React variant, it just modifies the TypeScript variant to amend the setup of `testing-library` that the React variant does so that it is compatible with TypeScript.

**Comment by eoinkelly** [comment]
@G-Rath Ah ok, that makes sense. In that case, it's a :shipit: from me

**Review by eoinkelly — APPROVED** [review]

**Review by mischa-s — APPROVED** [review]

**Pull request merged**
