### PR TITLE
Prettier changed it's mind and was breaking builds

### PR DESCRIPTION
**Pull request by eoinkelly**
Ok ~boomer~prettier.

### CODE REVIEW

**Comment by G-Rath** [comment]
I am curious in how this has happened however - our package constraint should have us using `prettier@1`, which when I run `yarn format-check` locally only warns about the `README.md`, unless I update to `prettier@2` 🤔 

(btw, we should update the package constraint to use `prettier@2`)

**Comment by G-Rath** [comment]
Yeah for some reason it's install [`prettier@2`](https://travis-ci.org/github/ackama/rails-template/jobs/668269834#L1542).

**Comment by eoinkelly** [comment]
Turns out we don't set a version constraint when we install it - see https://github.com/ackama/rails-template/blob/master/variants/frontend-base/template.rb#L16

**Comment by G-Rath** [comment]
Yeah I was just looking at that - because the problem is that when you give yarn a constraint for `add`, it'll write that exact constraint to the `package.json`.

i.e `prettier@2` will result in `prettier: "2"` being added, which while that is a valid constraint, I prefer the complete form as it's more explicit and uniform, a la `npm install prettier@2` -> `prettier: "^2.0.2"`.

I think there is enough merit in not having constraints to leave it for now, and then we can reevaluate if it turns out to be a problem too often.

**Pull request merged**
