### PR TITLE
Add bullet gem to Gemfile by default

### PR DESCRIPTION
**Pull request by l-suzuki**
✅ Resolves issue #62 
💎 Adds Bullet gem by default

### CODE REVIEW

**Comment by joshmcarthur** [comment]
@l-suzuki there's quite a few configurations available for bullet, that I think get generated when bullet is installed with `rails g`. I think there might be more to this feature - at least, running `rails g` for the user to generate the initializer. I think there may also be  set of sensible defaults we'd like to define in that initializer.

**Review by eoinkelly — CHANGES_REQUESTED** [review]
I agree with @joshmcarthur that we should consider setting some recommended default config. @l-suzuki do you have any recommended settings you like to use?

**Comment by JamesYang76** [comment]
I am going to look into it also.

**Comment by JamesYang76** [comment]
Below is generated by `bundle exec rails g bullet:install` , but `alert`, `console` and `add_footer` cannot execute  because of our default content security policy
```ruby
config.after_initialize do
      Bullet.enable        = true
      Bullet.alert         = true
      Bullet.bullet_logger = true
      Bullet.console       = true
    # Bullet.growl         = true
      Bullet.rails_logger  = true
      Bullet.add_footer    = true
    end 
```

**Comment by JamesYang76** [comment]
Because of `content security policy` configuration, we cannot use default bullet configuration, so I am going to use below settings
`config/environments/development.rb`
```ruby
# Bullet makes inline javascript, so there is warning in console in browse until content security policy change
  config.after_initialize do
    Bullet.enable        = true
    Bullet.raise         = true # raise an error if n+1 query occurs
    Bullet.bullet_logger = true
    Bullet.rails_logger  = true

    # Because it is against our default policy in content_security_policy.rb,
    # these do not execute until policy change,
    # Rails.application.config.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
    # policy.script_src  :self, :unsafe_inline
    # policy.style_src   :self, :unsafe_inline

    # Bullet.alert         = true
    # Bullet.console       = true
    # Bullet.add_footer    = true
  end
```

`config/environments/test.rb`
```ruby
config.after_initialize do
    Bullet.enable        = true
    Bullet.bullet_logger = true
    Bullet.raise         = true # raise an error if n+1 query occurs
  end
```

**Comment by JamesYang76** [comment]
@eoinkelly @joshmcarthur I've take this pr and change configuration

**Review by joshmcarthur — APPROVED** [review]

**Review by eoinkelly — APPROVED** [review]
:sparkles:

**Pull request merged**
