### PR TITLE
enable Redis and Sidekiq queue health checks

### PR DESCRIPTION
**Pull request by fractalcactus**

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]

**Comment by eoinkelly** [comment]
This change means that apps which don't use Sidekiq will fail health checks. I'm hesitant to have this be true because

1. We don't need background jobs for every app 
2. This change means that the app we generate would fail health checks out of the box unless you said _yes_ to the sidekiq variant - that doesn't seem like an ideal developer experience

@fractalcactus can you give me some more context on this change? It's entirely possible I'm missing something.

**Review by eoinkelly — CHANGES_REQUESTED** [review]
More discussion needed

**Comment by fractalcactus** [comment]
@eoinkelly I'm not sure why I can't find the original issue - from memory, it was sparse on details, I didn't know the context either. Thanks for catching this

**Comment by eoinkelly** [comment]
@fractalcactus I'm going to gently decline this because I don't think we have enough context on what problem this change is solving. :100: happy to help refine the problem statement if you feel there is more to do here.

**Pull request closed without merging**
